similarity_text/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('text_matching.urls'))
]

text_matching/urls.py
from django.urls import path
from .views import search, index


app_name = 'text_matching'

urlpatterns = [
    path('search', search, name='search'),
    path('', index, name='index'),
]

text_matching/models.py
from django.db import models

# Create your models here.

text_matching/views.py
from pathlib import Path

from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from ratelimit.decorators import ratelimit

from utility import TextSimilarity, read_single_col_in_dataset

file_path = Path(__file__).parent.parent.resolve()
DUMMY_MEDICAL_CSV = f'{file_path}/utility/Dummy medical dataset.csv'


@require_http_methods(["GET"])
@ratelimit(key='ip', rate='5/m', block=True)
def index(request):
    """This function is called when the user open the site
     Args:
         (object) request - contain request objects
     Return:
         http response contains the list of keys that used for similarity searching
    """
    medical_keys = read_single_col_in_dataset('Key', DUMMY_MEDICAL_CSV)
    return render(request, 'text_matching/index.html', {"keys": medical_keys})


@require_http_methods(["POST"])
@ratelimit(key='ip', rate='5/m', block=True)
def search(request):
    """This function is called when the user searches for similarity
    between the key he sends and the dummy medical values column in CSV
     Args:
         (object) request - contains request objects and the key that user sends it
     Return:
         http response contains two keys one for the key sent and other list of matching texts with that key
    """
    search_key = request.POST.get("key", None)
    if not search_key:
        messages.error(request, "Error search key not sent.")
    text_similarity = TextSimilarity(search_key, percentage=50)
    medical_values = read_single_col_in_dataset('Values', DUMMY_MEDICAL_CSV)
    matching_text = text_similarity.search_for_similarity(medical_values)
    if matching_text:
        return render(request, 'text_matching/similarity_table.html',
                      {"matching_text": matching_text, "key": search_key})
    else:
        messages.warning(request, "There is no similarity found.")
    return redirect('text_matching:index')


def handler429(request, exception):
    """This function are called when too many request occurs on endpoint
    when user exceed the maximum number of requests
    """
    template_name = 'text_matching/error_429.html'
    return render(request, template_name, locals())

templates/text_matching/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    {%block header%}
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Similarity Text Using Jaccard Index</title>

        {% block stylesheet %}
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        {% endblock stylesheet %}
    {% endblock header %}
</head>
<body>
    {% block content %}

    {% endblock content %}
</body>
</html>

templates/text_matching/error_429.html
{% extends 'text_matching/base.html' %}
{% block content %}
<div class="container">
    <!-- start main content -->
            <div class="row">
                <div class="col-12 m-auto text-center">
                    <h4>Too Many Request</h4>
                    <p class="alert alert-danger">
                        You're Blocked for minutes because too many requests were found.
                    </p>
                </div>
            </div>
    <!-- end main content -->
</div>
{% endblock content %}

templates/text_matching/index.html
{% extends 'text_matching/base.html' %}
{% block content %}
    <div class="text-center mt-5">Text Similarity Check</div>
    {% include "text_matching/search.html" %}
{% endblock content %}

templates/text_matching/search.html
<form action="{% url 'text_matching:search' %}" method="post" class="mt-5 mx-5">
<div class="form-group">
    {% csrf_token %}
    <div class="row">
        <div class="col-6">
         <select class="form-select" name="key" aria-label="Similarity Select">
            <option value="">Select From Menu</option>
             {% for key in keys %}
                <option value="{{ key }}">{{ key }}</option>
            {% endfor %}
        </select>
        </div>
        <div class="col-6">
            <input class="btn btn-primary" type="submit" value="Submit">
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-6">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li class="alert alert-warning">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>
</form>

templates/text_matching/similarity_table.html
{% extends 'text_matching/base.html' %}
{% block content %}
<div class="text-center my-3">Text Matching Similarity above 50%</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Keys</th>
      <th scope="col">Value</th>
      <th scope="col">Matching Percentage</th>
    </tr>
  </thead>
  <tbody>
  {% for matched_item in matching_text %}
        <tr>
            {% if forloop.first %}
                <td rowspan="{{ matching_text|length }}">{{ key }}</td>
                {% endif %}
            <td>{{ matched_item.value }}</td>
            <td>{{ matched_item.score }}</td>
        </tr>
    {% endfor %}
  </tbody>
</table>
<a href="{% url 'text_matching:index' %}">Return to Search</a>
{% endblock %}